### ISSUE TITLE
amazon-corretto-8.302.08.1-windows-x64-jre.msi FeatureAddPath adds wrong entry to PATH-variable

### ISSUE THREAD

**Issue by wolfbardo** [corretto/corretto-8#330] opened 2021-09-27 12:05 UTC
### Describe the bug
msi-Installation of amazon-corretto-8.302.08.1-windows-x64-jre.msi 
leads to a wrong system Path Entry starting with

bin;%SystemRoot%\system32;%SystemRoot%;%SystemRoot%\System32\Wbem;%SYSTEMROOT%\System32\WindowsPowerShell\v1.0\...

### To Reproduce
Standard-Installation via

msiexec.exe -i amazon-corretto-8.302.08.1-windows-x64-jre.msi /l* "c:\tmp\\amazon8x64.install_log.txt"

or 

msiexec /i "amazon-corretto-8.302.08.1-windows-x64-jre.msi" /l* "c:\opsi.org\log\\amazon8x64.install_log.txt" /qb-! ALLUSERS=1 REBOOT=ReallySuppress"

### Expected behavior
System Path Variable should be

C:\Program Files\\Amazon Corretto\\jre8\bin\bin;%SystemRoot%\system32;%SystemRoot%;%SystemRoot%\System32\Wbem;%SYSTEMROOT%\System32\WindowsPowerShell\v1.0\...

### Screenshots
![Screenshot_kvm12190964_2021-09-27_14:00:48](https://user-images.githubusercontent.com/91467077/134904454-01eb3f5e-d4c4-4dad-88c9-eed37a757417.png)

### Platform information
OS win 10 1909 64 and win10 20h2 64

openjdk version "1.8.0_302"
OpenJDK Runtime Environment Corretto-8.302.08.1 (build 1.8.0_302-b08)
OpenJDK 64-Bit Server VM Corretto-8.302.08.1 (build 25.302-b08, mixed mode)

**Comment by steffmeister** [comment] 2021-09-28 09:19
I also ran into this issue and I think the problem is this (but I am not a MSI expert ... ):
![image](https://user-images.githubusercontent.com/1689735/135059880-50a9df8b-5893-400d-aa09-b8ac7799b8f7.png)

Here should be CorrettoJRE instead of CorrettoJDK I think. The JDK MSI is working correctly btw.

**Comment by TianminShi** [comment] 2021-09-28 17:35
Hi wolfbardo, thank you for reporting this issue to us. we have identified the issue and actively working on fixing it.

**Comment by MrMikeJJ** [comment] 2021-10-15 11:09
@steffmeister 
I edited that with Orca and your suggestion is correct. That fixes it.
Since "bin" is in the Directory table, replacing the Path value with 
`[bin];[~]`
also works
thanks
Mike

**Comment by TianminShi** [comment] 2021-10-29 22:08
Hi @wolfbardo, @steffmeister and @MrMikeJJ,  this issue should be fixed in release [8.312.07.1](https://github.com/corretto/corretto-8/releases/tag/8.312.07.1) and thank you again for report this issue to us.

**Closed as completed by TianminShi** 2021-10-29 22:08 UTC
Labels: bug
