### ISSUE TITLE
OpenJDK Issue - JDK-8285445

### ISSUE THREAD

**Issue by lloyd-j0nes** [corretto/corretto-8#385] opened 2022-04-25 21:06 UTC
After upgrading to Corretto 8 Update 332, our developers are seeing this issue with undertow that has recently been fixed in OpenJDK (but not Corretto yet):

https://bugs.openjdk.java.net/browse/JDK-8285445

This is on multiple Windows 10 build 20H2/21H2 machines.

**Comment by alvdavi** [comment] 2022-04-25 21:19
Hi,

The recent 8u332 update did include the regression that you mentioned. The issue is in the process of being backported to the different OpenJDK updates projects (including jdk8u). Until a fix is available, the stated workaround to set `-Djdk.io.File.enableADS=true` should fix the issue. The workaround has no side effect and the patch proposed for JDK-8285445 just sets its value to true by default

**Comment by alvdavi** [comment] 2022-06-28 16:34
This patch is already scheduled for our next release. I'm closing this as duplicate of #383 which we will keep open until the release happens

**Closed as completed by alvdavi** 2022-06-28 16:34 UTC
Labels: bug
