### ISSUE TITLE
Linux requires GLIBC_2.14 or greater

### ISSUE THREAD

**Issue by lordbuddha** [corretto/corretto-8#17] opened 2018-11-19 09:37 UTC
Converted the rpm to a tgz so I could try without installing on a RHEL 6 server only to find that the preview requires GLIBC_2.14 or greater.....   The RHEL 6 has GLIBC_2.12.

I see the OpenJDK from https://www.azul.com/downloads/zulu/zulu-linux/  will work on GLIBC_2.5...

It would be nice / useful if corretto-8 would run on older OS's.

**Comment by yishaigalatzer** [comment] 2018-11-19 23:11
[Life Cycle Dates](https://access.redhat.com/support/policy/updates/errata#Life_Cycle_Dates) indicate that RHEL 6 is still under maintenance until Nov 30, 2020 (and extended support until 2024).

**Comment by EricEdens** [comment] 2018-11-21 00:52
@lordbuddha, it appears this is a duplicate of #10 (or at least would be solved by it), so I'll go ahead and close this. If that's not the case, feel free to re-open this issue!

**Comment by EricEdens** [comment] 2018-11-21 00:53
Duplicate of #10

**Closed by EricEdens** 2018-11-21 00:53 UTC
Labels: enhancement

**Comment by lordbuddha** [comment] 2018-11-21 05:18
Will open again because it does not.
