### ISSUE TITLE
Corretto 8 alpine jre missing JAVA path

### ISSUE THREAD

**Issue by TheHydGuy** [corretto/corretto-8#371] opened 2022-03-23 22:13 UTC
### Describe the bug
The latest version of Corretto:8-alpine-jre is missing JAVA path

### To Reproduce
Running the following command fails to output the Java version
 docker run amazoncorretto:8-alpine java -version

### Expected behavior
Docker run should return the jdk version information.

This worked till yesterday (March 22, 2022) and started failing today.

**Comment by lutkerd** [comment] 2022-03-23 22:42
Duplicate of https://github.com/corretto/corretto-docker/issues/92

**Closed as completed by lutkerd** 2022-03-23 22:42 UTC
Labels: bug
