### ISSUE TITLE
Running Eclipse 2019-03 with macOS Corretto-8 too many 'spinning-cursor-beachballs'

### ISSUE THREAD

**Issue by normanm-algonquin** [corretto/corretto-8#120] opened 2019-04-25 02:46 UTC
### Describe the bug
Running most recent Eclipse IDE (2019-03) with the most recent Correto-8 JDK on Mac causes many 'spinning-cursor-beachballs', approx. 1 every minute or so.

### To Reproduce
In eclipse.ini add following two lines at top of file:
  -vm
  /Library/Java/JavaVirtualMachines/amazon-corretto-8.jdk/Contents/Home/bin/
then just use the IDE normally to edit, compile and debug Java code.

### Expected behavior
Running with Oracle's JDK (for example 1.8.0_192)  produces beachballs at the 'normal' rate for Eclipse IDE, perhaps 1 or 2 a day.

### Screenshots
sorry, can't snapshot the spinning cursor

### Platform information
    OS: macOS
    Version: OpenJDK Runtime Environment Corretto-8.212.04.2 (build 1.8.0_212-b04)

### Additional context
I believe with Oracle's JDK the setting "-XstartOnFirstThread" is supposed to manage this behaviour

**Comment by davecurrie** [comment] 2019-04-25 03:14
Hi @normanm-algonquin. Thanks for getting in touch.

I have tried to reproduce the issue and it's not giving me the same issue. Have you tried with another OpenJDK distribution (of the same version, 8u212) to see if it gives you the same result?

**Comment by normanm-algonquin** [comment] 2019-04-25 03:22
I can try some of the others: Adopt, Azul and Liberica have Mac packages

**Comment by davecurrie** [comment] 2019-04-25 03:25
Any of those will work. There should be nothing specifically in Corretto that causes this behavior.

**Comment by davecurrie** [comment] 2019-04-29 17:12
@normanm-algonquin Have you been able to reproduce this behavior or confirm it only happens in Corretto?

**Comment by normanm-algonquin** [comment] 2019-04-29 17:23
I have tried Amazon, Liberica and Zulu and I believe the problem is with one of the Eclipse plugins - Payara Tools throws an exception in 
`IPayaraRuntimeModel.JavaRuntimeEnvironment: JdkDefaultValueService.compute()`
which I believe is triggered by parsing Payara's domain.xml

There are A LOT of JVM args, are any of them likely to be an issue?

`
<java-config classpath-suffix="" debug-options="-agentlib:jdwp=transport=dt_socket,server=y,suspend=n,address=9009" system-classpath="">

        <jvm-options>-client</jvm-options>
        <jvm-options>-Djava.awt.headless=true</jvm-options>
        <jvm-options>-Djdk.corba.allowOutputStreamSubclass=true</jvm-options>
        <jvm-options>-Djavax.xml.accessExternalSchema=all</jvm-options>
        <jvm-options>-Djavax.management.builder.initial=com.sun.enterprise.v3.admin.AppServerMBeanServerBuilder</jvm-options>
        <jvm-options>-XX:+UnlockDiagnosticVMOptions</jvm-options>
        <jvm-options>-Djava.endorsed.dirs=${com.sun.aas.installRoot}/modules/endorsed${path.separator}${com.sun.aas.installRoot}/lib/endorsed</jvm-options>
        <jvm-options>-Djava.security.policy=${com.sun.aas.instanceRoot}/config/server.policy</jvm-options>
        <jvm-options>-Djava.security.auth.login.config=${com.sun.aas.instanceRoot}/config/login.conf</jvm-options>
        <jvm-options>-Dcom.sun.enterprise.security.httpsOutboundKeyAlias=s1as</jvm-options>
        <jvm-options>-Xmx512m</jvm-options>
        <jvm-options>-Djavax.net.ssl.keyStore=${com.sun.aas.instanceRoot}/config/keystore.jks</jvm-options>
        <jvm-options>-Djavax.net.ssl.trustStore=${com.sun.aas.instanceRoot}/config/cacerts.jks</jvm-options>
        <jvm-options>-Djava.ext.dirs=${com.sun.aas.javaRoot}/lib/ext${path.separator}${com.sun.aas.javaRoot}/jre/lib/ext${path.separator}${com.sun.aas.instanceRoot}/lib/ext</jvm-options>
        <jvm-options>-Djdbc.drivers=org.apache.derby.jdbc.ClientDriver</jvm-options>
        <jvm-options>-DANTLR_USE_DIRECT_CLASS_LOADING=true</jvm-options>
        <jvm-options>-Dcom.sun.enterprise.config.config_environment_factory_class=com.sun.enterprise.config.serverbeans.AppserverConfigEnvironmentFactory</jvm-options>
        <jvm-options>-Dorg.glassfish.additionalOSGiBundlesToStart=org.apache.felix.shell,org.apache.felix.gogo.runtime,org.apache.felix.gogo.shell,org.apache.felix.gogo.command,org.apache.felix.shell.remote,org.apache.felix.fileinstall</jvm-options>
        <jvm-options>-Dosgi.shell.telnet.port=6666</jvm-options>
        <jvm-options>-Dosgi.shell.telnet.maxconn=1</jvm-options>
        <jvm-options>-Dosgi.shell.telnet.ip=127.0.0.1</jvm-options>
        <jvm-options>-Dgosh.args=--nointeractive</jvm-options>
        <jvm-options>-Dfelix.fileinstall.dir=${com.sun.aas.installRoot}/modules/autostart/</jvm-options>
        <jvm-options>-Dfelix.fileinstall.poll=5000</jvm-options>
        <jvm-options>-Dfelix.fileinstall.log.level=2</jvm-options>
        <jvm-options>-Dfelix.fileinstall.bundles.new.start=true</jvm-options>
        <jvm-options>-Dfelix.fileinstall.bundles.startTransient=true</jvm-options>
        <jvm-options>-Dfelix.fileinstall.disableConfigSave=false</jvm-options>
        <jvm-options>-XX:NewRatio=2</jvm-options>
        <jvm-options>-Dcom.ctc.wstx.returnNullForDefaultNamespace=true</jvm-options>
        <jvm-options>-Djdk.tls.rejectClientInitiatedRenegotiation=true</jvm-options>
        <jvm-options>-Dorg.jboss.weld.serialization.beanIdentifierIndexOptimization=false</jvm-options>
        <jvm-options>-Dorg.glassfish.grizzly.DEFAULT_MEMORY_MANAGER=org.glassfish.grizzly.memory.HeapMemoryManager</jvm-options>
        <jvm-options>-Dorg.glassfish.grizzly.nio.DefaultSelectorHandler.force-selector-spin-detection=true</jvm-options>
        <jvm-options>[1.8.0|1.8.0u120]-Xbootclasspath/p:${com.sun.aas.installRoot}/lib/grizzly-npn-bootstrap-1.6.jar</jvm-options>
        <jvm-options>[1.8.0u121|1.8.0u160]-Xbootclasspath/p:${com.sun.aas.installRoot}/lib/grizzly-npn-bootstrap-1.7.jar</jvm-options>
        <jvm-options>[1.8.0u161|1.8.0u190]-Xbootclasspath/p:${com.sun.aas.installRoot}/lib/grizzly-npn-bootstrap-1.8.jar</jvm-options>
        <jvm-options>[1.8.0u191|1.8.0u500]-Xbootclasspath/p:${com.sun.aas.installRoot}/lib/grizzly-npn-bootstrap-1.8.1.jar</jvm-options>
      </java-config>
`

**Comment by davecurrie** [comment] 2019-04-29 18:55
It's hard to tell. Like you say, there are a lot of options there. I'm resolving this issue since it doesn't seem to be related to Corretto but if anyone from the team has an idea, I'll get them to update here.

**Closed by davecurrie** 2019-04-29 18:55 UTC
