### ISSUE TITLE
Crash on building fastdebug

### ISSUE THREAD

**Issue by nathan-jkn** [corretto/corretto-8#374] opened 2022-03-31 04:59 UTC
Hi Corretto Team, 

Thanks so much in advance, I'm hoping you can help me.

Regards,
Nathan

### Describe the bug
When I build from source using the debug_level of fastdebug, the build crashes.

### To Reproduce

I follow these steps to build.  
```
git clone https://github.com/corretto/corretto-8.git
cd corretto-8/
curl -s "https://get.sdkman.io" | bash
source "$HOME/.sdkman/bin/sdkman-init.sh"
sdk install gradle 7.4.1
yum install patch gtk+-devel gtk2-devel gtk3-devel libXtst-devel libXt-devel libXrender-devel cups-devel alsa-lib-devel
mv /usr/java/latest/jre/lib/ext/jfxrt.jar /usr/java/latest/jre/lib/ext/jfxrt.bak
gradle wrapper
./gradlew -Pcorretto.debug_level=fastdebug :installers:linux:universal:tar:build
```

They work fine if no debug_level is specified.  When debug level is specified the build fails.  It seems to be attempting to use keytools in the :installers:linux:universal:tar:importAmazonCacerts and the Java process is crashing with this error

```
#  Internal Error (/root/corretto-8/installers/linux/universal/tar/corretto-build/buildRoot/src/hotspot/src/share/vm/runtime/thread.hpp:670), pid=63271, tid=0x00007f0af9366700
#  assert(!current->_wx_init) failed: second init
```

### Expected behavior
The build succeeds

### Screenshots
N/A

### Platform information
```
[root@my corretto-8]# cat /etc/os-release
NAME="Amazon Linux"
VERSION="2"
ID="amzn"
ID_LIKE="centos rhel fedora"
VERSION_ID="2"
PRETTY_NAME="Amazon Linux 2"
ANSI_COLOR="0;33"
CPE_NAME="cpe:2.3:o:amazon:amazon_linux:2"
HOME_URL="https://amazonlinux.com/"
```

This is running in an Oracle Virtualbox VM inside of a Mac

### Additional context
This is end of the log where the build crashes
```
----- Build times -------
Start 2022-03-31 04:02:56
End   2022-03-31 04:21:34
00:00:24 corba
00:00:35 demos
00:11:40 hotspot
00:00:36 images
00:00:17 jaxp
00:00:22 jaxws
00:03:37 jdk
00:00:54 langtools
00:00:11 nashorn
00:18:38 TOTAL
-------------------------
Finished building OpenJDK for target 'images'

> Task :installers:linux:universal:tar:importAmazonCacerts FAILED
# To suppress the following error report, specify this argument
# after -XX: or in .hotspotrc:  SuppressErrorAt=/thread.hpp:670
#
# A fatal error has been detected by the Java Runtime Environment:
#
#  Internal Error (/root/corretto-8/installers/linux/universal/tar/corretto-build/buildRoot/src/hotspot/src/share/vm/runtime/thread.hpp:670), pid=63271, tid=0x00007f0af9366700
#  assert(!current->_wx_init) failed: second init
#
# JRE version:  (8.0_322-b06) (build )
# Java VM: OpenJDK 64-Bit Server VM (25.322-b06-fastdebug mixed mode linux-amd64 compressed oops)
# Failed to write core dump. Core dumps have been disabled. To enable core dumping, try "ulimit -c unlimited" before starting Java again
#
# An error report file with more information is saved as:
# /root/corretto-8/installers/linux/universal/tar/corretto-build/buildRoot/src/build/linux-x86_64-normal-server-fastdebug/images/j2sdk-image/hs_err_pid63271.log
#
# If you would like to submit a bug report, please visit:
#   https://github.com/corretto/corretto-8/issues/
#
Current thread is 139685107492608
Dumping core ...

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':installers:linux:universal:tar:importAmazonCacerts'.
> Process 'command 'bin/keytool'' finished with non-zero exit value 134

* Try:
> Run with --stacktrace option to get the stack trace.
> Run with --info or --debug option to get more log output.
> Run with --scan to get full insights.

* Get more help at https://help.gradle.org

Deprecated Gradle features were used in this build, making it incompatible with Gradle 8.0.

You can use '--warning-mode all' to show the individual deprecation warnings and determine if they come from your own scripts or plugins.

See https://docs.gradle.org/7.4.1/userguide/command_line_interface.html#sec:command_line_warnings

BUILD FAILED in 22m
10 actionable tasks: 10 executed

```

When the build crashes it leaves behind this error file

[hs_err_pid63271.log](https://github.com/corretto/corretto-8/files/8386078/hs_err_pid63271.log)

Again, thanks so much.  Any help is appreciated.

**Comment by benty-amzn** [comment] 2022-04-05 21:09
Hi, thanks for contacting us about this. We're still investigating the issue and will provide an update soon.

**Comment by olivergillespie** [comment] 2022-04-06 11:20
I can reproduce the issue on Amazon Linux 2 directly. It occurs with any invocation of the built keytool binary, or java itself directly, for example:

```
./installers/linux/universal/tar/corretto-build/buildRoot/src/build/linux-x86_64-normal-server-fastdebug/jdk/bin/keytool
./installers/linux/universal/tar/corretto-build/buildRoot/src/build/linux-x86_64-normal-server-fastdebug/jdk/bin/java
```

both lead to:

```
#  assert(!current->_wx_init) failed: second init
```

Ignoring the error (`-XX:SuppressErrorAt=/thread.hpp:670`) leads to another failing assert nearby on line 676.

I haven't yet reproduced on upstream OpenJDK8, the java and keytool binaries resulting from a fastdebug build there seem to work fine.

The failing assert was introduced 5 months ago in https://github.com/corretto/corretto-8/commit/c68e8ecfa91b33916d3b2efe4f223c203b10400c.

More investigation required.

**Comment by olivergillespie** [comment] 2022-04-06 11:59
I suspect the issue is that https://github.com/corretto/corretto-8/blame/develop/src/hotspot/src/share/vm/runtime/thread.hpp#L666 is not explicitly initialized, so it (sometimes?) gets initialized as true, which is not what is expected by the assertions. It's expected to start as false and be set once.

**Comment by olivergillespie** [comment] 2022-04-06 12:08
It appears to be correctly initialized to false in the Thread constructor in upstream tip (https://github.com/openjdk/jdk/blob/b9cc3bc1bf61572f2813f057eea7326fd0c2bd14/src/hotspot/share/runtime/thread.cpp#L279), but not in the backport to JDK11 (https://github.com/openjdk/jdk11u-dev/blob/master/src/hotspot/share/runtime/thread.hpp#L757-L765) or here in Corretto 8. If I'm right that it's also broken in JDK11, it might have been missed until now because it's gated only for Mac M1 builds, whereas the Corretto 8 backport enables the new assertions for all platforms.

**Comment by olivergillespie** [comment] 2022-04-06 13:06
To unblock you while we fix it, you can comment out the assertion on lines 670, 676 and 683 of `src/hotspot/src/share/vm/runtime/thread.hpp` and it should work.

Simply initializing _wx_init to false in the constructor is not enough, it helps with the currently failing assertion but then 676 fails in `classLoader.cpp` executing:
```
ThreadToNativeFromVM ttn(thread);
Thread::WXExecFromWriteSetter wx_exec;
```

**Comment by olivergillespie** [comment] 2022-04-06 18:40
Should be fixed by https://github.com/corretto/corretto-8/pull/375, feel free to reopen if not.

**Comment by nathan-jkn** [comment] 2022-04-06 18:41
Thanks @olivergillespie!  Much appreciated

**Closed as completed by olivergillespie** 2022-04-06 18:40 UTC
Labels: bug
