### ISSUE TITLE
Nepali charaters

### ISSUE THREAD

**Issue by LoZzR** [corretto/corretto-8#195] opened 2019-12-04 13:35 UTC
I work on an application that must generate a confirmation form (pdf file) with nepali characters. When I passed from Oracle JDK to Corretto JDK, the nepali characters are not anymore well displayed in the generated form. I use a Graphics2D object returned by createGraphics method of the BufferedImage class to draw the text into the bufferd image.

**Comment by ziyiluo** [comment] 2019-12-04 21:09
@LoZzR Can you give us a code snippet to reproduce your issue? Besides, can you tell us on which platform (OS, Corretto version) did you observe the issue?

**Comment by ziyiluo** [comment] 2019-12-04 21:49
@LoZzR Besides, would you please also give us a screenshot of how the characters are not displayed correctly?

**Comment by LoZzR** [comment] 2019-12-05 10:22
@ziyiluo I use Correto 8  (jdk1.8.0_232) on a Windows 10 machine, here is the code where the problem occurs(codeDrawing.png DataBufferedImage.png)  and the result with Oracle (withOracle.png) vs Corretto (withCorretto.png
![codeDrawing](https://user-images.githubusercontent.com/23581387/70226621-715e0b80-1751-11ea-87f0-6318cea817c5.PNG)
![DataBufferdImage](https://user-images.githubusercontent.com/23581387/70226622-71f6a200-1751-11ea-97ea-15aa8668fcd5.PNG)
![withOracle](https://user-images.githubusercontent.com/23581387/70226623-71f6a200-1751-11ea-8b09-76007525ea22.PNG)
![withCorretto](https://user-images.githubusercontent.com/23581387/70226624-71f6a200-1751-11ea-8ac4-ca90e5935847.PNG)



)

**Comment by ziyiluo** [comment] 2019-12-11 01:11
@LoZzR I was able to reproduce the problem. One difference between OracleJDK8 and OpenJDK8 is that the latter does not bundle Lucida fonts. From my reproduction tests, When the font I specified in code does not support Nepali characters, the JDK will automatically fall back to search for Lucida ("Lucida Sans" does support Nepali). Corretto-8 was able to draw the characters correctly when Lucida Sans is installed on Windows.

May I ask which font you are using because it's unclear from your code? My guess is that your font does not support Nepali characters. If that's the case, you need to decide which font to use for Nepali and bundle it with your application if it is not a system font.

**Comment by LoZzR** [comment] 2019-12-16 10:48
@ziyiluo Thank you for this analysis, Corretto-8 was able to draw the characters correctly when I installed Lucida Sans on Windows (LucidaSansRegular.ttf and LucidaSansDemiBold.ttf)

**Comment by ziyiluo** [comment] 2019-12-20 00:13
Good to know! I'm closing this issue. Feel free to reopen it if you have further questions.

**Closed by ziyiluo** 2019-12-20 00:13 UTC
