### ISSUE TITLE
JRE Availability for corretto 8

### ISSUE THREAD

**Issue by bharanitharanm** [corretto/corretto-8#365] opened 2022-03-07 16:02 UTC
We are using Ubuntu 20.04 and Corretto JRE 8 is not available for Ubuntu. But JDK is available, In our systems we need only JRE and not JDK. How to get Amazon Corretto JRE 8 for Ubuntu 20.04?

**Comment by caojoshua** [comment] 2022-03-08 19:01
We currently only provide JDK packages for Corretto 8. Please see https://github.com/corretto/corretto-8/issues/45, and you can plus one that issue.

**Comment by benty-amzn** [comment] 2022-04-06 20:13
Closing this as a duplicate of #45 for now

**Closed as completed by benty-amzn** 2022-04-06 20:13 UTC
