### ISSUE TITLE
Swing font rendering has character spacing issues

### ISSUE THREAD

**Issue by SRZC** [corretto/corretto-8#148] opened 2019-07-02 07:12 UTC
**Related to:**

- JDK: Amazon Corretto 1.8.0 212
- OS: Microsoft Windows [Version 10.0.17134.829]

**Behavior:**
Font rendering puts more space between characters than other JDKs. Please see attached screenshot. It shows a comparison between Corretto 1.8.0.212, AdoptJDK 1.8.0.212 and Oracle JDK 1.8.0.152. As you can see Corretto puts more space before and after the caracters in the word "REPORTING". As this is not happening with Adopt I open this bug for Corretto and not OpenJDK.

![font_rendering_issue](https://user-images.githubusercontent.com/40888713/60491538-4f93c080-9ca9-11e9-9122-cc586cb7e979.PNG)

**Example:**
This is the code I used to create the screenshot.

```java
import java.awt.Font;
import java.awt.GridLayout;
import java.util.ArrayList;
import java.util.List;

import javax.swing.JFrame;
import javax.swing.JLabel;
import javax.swing.UnsupportedLookAndFeelException;


public class CorrettoSwingFontExample {

	public static void main(String[] args) throws ClassNotFoundException, InstantiationException, IllegalAccessException, UnsupportedLookAndFeelException {

		List<String> fontNames = new ArrayList<String>();
		fontNames.add(null); // default font
		fontNames.add("Dialog");
		fontNames.add("DialogInput");
		fontNames.add("Monospaced");
		fontNames.add("Serif");
		fontNames.add("SansSerif");
		fontNames.add("Arial");

		JFrame jFrame = new JFrame();
		jFrame.getContentPane().setLayout(new GridLayout(fontNames.size(), 1));

		for (String fontName : fontNames) {
			Font font = fontName == null ? new JLabel().getFont() : new Font(fontName, Font.BOLD, 12);

			JLabel jLabel = new JLabel("REPORTING; " + font);
			jLabel.setFont(font);

			jFrame.getContentPane().add(jLabel);
		}

		jFrame.setTitle(System.getProperty("java.vendor") + ", " + System.getProperty("java.version"));

		jFrame.setSize(1000, 50 + fontNames.size() * 25);

		jFrame.setVisible(true);

	}

}
```

Contact me in case you need more data.

Best wishes
Stefan

**Comment by SRZC** [comment] 2019-07-02 07:23
It seems there is a bug in JDK 11 which causes the same issues: https://bugs.openjdk.java.net/browse/JDK-8214538

**Comment by ziyiluo** [comment] 2019-07-02 19:51
@SRZC we are looking at your issue. Meanwhile, would you tell us your use case and how bad this issue has affected your application? Also just asking, have you tested the issue on platforms other than Windows?

**Comment by SRZC** [comment] 2019-07-03 08:02
@ziyiluo thank you for your feedback. Here is an update regarding your questions.

**Use case**
We use Swing for the user interface of our application BACKUP EAGLE(R) see www.backupeagle.com

**Impact**
We cannot release our UI with the font rendering issues. We rate this as non acceptable for the users. However we can ship a workaround (see text below) so there would be no impact for the users. Therefore we rate this as low impact.

**Linux results**
I have tested the issue on Ubuntu 18.04 LTS with xfce and have the same result. See the green boxes in the following screenshot.

Please note: When doing "export FREETYPE_PROPERTIES=truetype:interpreter-version=35" before starting the UI the font rendering is like the one in Oracle JDK 1.8.0_152.

I found this info in https://bugs.openjdk.java.net/browse/JDK-8217731
This bug is fixed there. Maybe the fix needs to be backported to Amazon Corretto 1.8.0.

From the corretto release notes I see:
> 8.212.04.2 improves handling of TrueType fonts (JDK-8219066). The following platforms are updated: ...
Maybe this is the issue of the problems.

![font_rendering_issue_ubuntu_18-4-xfce-w-comments](https://user-images.githubusercontent.com/40888713/60573997-fdba6b80-9d78-11e9-8ffa-6f988d5fc47a.png)

Best wishes
Stefan

**Comment by ziyiluo** [comment] 2019-07-17 17:45
@SRZC Apologize for the delay. We identified the issue to be caused by the version of [Freetype](https://www.freetype.org/) bundled in Corretto. Freetype is used in OpenJDK as the font renderer. In Corretto versions before 8.212.04.3, the bundled Freetype version in Windows builds is 2.5 (released in 2013). We ran your code using the old Corretto and the font rendering was the same as Oracle's. In 8.212.04.x, we updated Freetype to be the latest at that time (i.e., 2.9.1), which causes the spacing issue you observed. We also observed the same issue in Zulu JDK as it also bundles a relatively new Freetype.

the Corretto team is still discussing the right action item for this issue. We still want to bundle the latest Freetype as it fixes other issues and it is recommended by the Freetype project. We will come back to you once we have a decision.

Btw, unlike Windows, Corretto Linux build does not bundle Freetype. The font rendering depends on the `libfreetype.so` installed on the system.

**Comment by JonasWilms** [comment] 2019-08-19 09:12
Couldn't you just backport the JDK 11 solution?

Bundling 2.9.1, but setting the interpreter-version to 35 by default:
https://bugs.openjdk.java.net/browse/JDK-8217731

**Comment by JonasWilms** [comment] 2019-09-04 15:22
Thank you @alvdavi for contributing the backport. Will the Coretto 8u232 release also be on October 15?

**Comment by alvdavi** [comment] 2019-09-04 15:37
@JonasWilms up until know we have managed to release Corretto on the same day of the OpenJDK release and we plan to continue doing so.

**Comment by alvdavi** [comment] 2019-10-18 03:48
Hi,

We released Corretto two days ago and it contains this fix, so I will proceed to close the issue. Please, let us know if the issue persists.

**Closed by alvdavi** 2019-10-18 03:48 UTC
Labels: bug
