### ISSUE TITLE
No Image Display in HTML-Labels

### ISSUE THREAD

**Issue by subruch** [corretto/corretto-8#123] opened 2019-05-07 10:00 UTC
The IMG-Tag is not working in JLabels.

Images are not displayed in Coretto.
Tested on Windows and Linux.

Example source code:

```java
import java.awt.BorderLayout;
import javax.swing.JFrame;
import javax.swing.JLabel;
import javax.swing.JPanel;


public class HtmlImageDemo extends JFrame
{
    public static void main(String s[])
    {
        HtmlImageDemo frame = new HtmlImageDemo();
    }


    HtmlImageDemo()
    {
        JPanel panel = new JPanel();
        panel.setLayout(new BorderLayout());

        JLabel label = new JLabel("<html><body>No Image in Coretto:<br><img src=\"https://picsum.photos/id/237/800/750\"></body></html>");
        panel.add(label, BorderLayout.CENTER);

        add(panel);
        setSize(800, 800);
        setLocationRelativeTo(null);
        setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
        setVisible(true);
    }
}
```

**Comment by alvdavi** [comment] 2019-05-07 23:16
Hi,

Thanks for the report. This is not affecting Corretto only, but all OpenJDK 8u202+ versions (11.0.2 and higher are also affected). The problem is listed on [JDK-8218674](https://bugs.openjdk.java.net/browse/JDK-8218674).

I've back-ported the patch listed in JDK-8218674 and your sample code did display the image. However, this is not the kind of fix we want to do directly in Corretto, we will see if we can ensure this gets fixed in the OpenJDK upstream repositories.

**Comment by alvdavi** [comment] 2019-05-07 23:43
We will work on back-porting this to OpenJDK8 and OpenJDK11, I'll post any updates here

**Comment by alvdavi** [comment] 2019-05-09 21:41
The fix has now been pushed to openjdk8u222, so future versions of Corretto (or other OpenJDK based distributions) will no longer be affected.

The backport entry is:
https://bugs.openjdk.java.net/browse/JDK-8223659

**Closed by alvdavi** 2019-05-09 21:41 UTC
