### ISSUE TITLE
cann't execute sun.misc.Unsafe --> putLong  Method 

### ISSUE THREAD

**Issue by ZZD3627** [corretto/corretto-8#388] opened 2022-05-16 14:33 UTC
```   
                                     -----error:detail-----
#
# A fatal error has been detected by the Java Runtime Environment:
#
#  SIGSEGV (0xb) at pc=0x00007f5922fd3032, pid=215926, tid=0x00007f58ddedb700
#
# JRE version: OpenJDK Runtime Environment (8.0_312-b07) (build 1.8.0_312-b07)
# Java VM: OpenJDK 64-Bit Server VM (25.312-b07 mixed mode linux-amd64 compressed oops)
# Problematic frame:
# V  [libjvm.so+0x703032]  jni_IsInstanceOf+0x82
#
# Failed to write core dump. Core dumps have been disabled. To enable core dumping, try "ulimit -c unlimited" before starting Java again
#
# If you would like to submit a bug report, please visit:
#   https://github.com/corretto/corretto-8/issues/
#

```

**Comment by lutkerd** [comment] 2022-05-16 17:45
Hello,
Can you provide some more context on this issue? The full hs_err log would be helpful as well as any information about the code being executed that you can share.

Thanks.

**Comment by ZZD3627** [comment] 2022-05-17 14:07
Hi,
I am using corretto-1.8.0_312 on the unbuntu20.04 system. 
[hs_err_pid352364.log](https://github.com/corretto/corretto-8/files/8708927/hs_err_pid352364.log)


Here‘s my code:
`
import org.junit.jupiter.api.Test;
import org.springframework.boot.test.context.SpringBootTest;
import sun.misc.Unsafe;

import java.lang.reflect.Field;
import java.lang.reflect.Modifier;
import java.util.HashSet;

@SpringBootTest
class ShallowCopyTests {

    private Unsafe unsafe;

    @Test
    void testShallowCopy() throws NoSuchFieldException, IllegalAccessException {
        //获取Unsafe对象
        Field theUnsafe = Unsafe.class.getDeclaredField("theUnsafe");
        theUnsafe.setAccessible(true);
        unsafe = (Unsafe) theUnsafe.get(null);
        //创建一个对象
        Guard guard = new Guard();
        Object copy = shallowCopy(guard);
        System.out.println(copy.toString());

    }

     Object shallowCopy(Object obj) throws NoSuchFieldException, IllegalAccessException {
        //获取此对象的size
        long size = sizeOf(obj);
        //将对象转换为其在内存中的地址
        long start = toAddress(obj);
        //分配一个新的本机内存块，其大小为给定大小（以字节为单位）
        long address = getUnsafe().allocateMemory(size);
        //将给定内存块中的所有字节设置为另一个块的副本
        getUnsafe().copyMemory(start, address, size);
        return fromAddress(address);
    }

    //将对象转换为其在内存中的地址，反之亦然。
     long toAddress(Object obj) {
        Object[] array = new Object[]{obj};
        //返回树组类的存储分配中第一个元素的偏移量。如果 arrayIndexScale 为同一类返回非零值，则可以使用该比例因子以及此基本偏移量来形成新的偏移量，以访问给定类的数组元素。
        long baseOffset = getUnsafe().arrayBaseOffset(Object[].class);
        return normalize(getUnsafe()
                .getInt(array, baseOffset)); //从给定的 Java 变量中获取值。
    }

    //将内存中的地址转化为对象
     Object fromAddress(long address) {
        Object[] array = new Object[]{null};
        long baseOffset = getUnsafe().arrayBaseOffset(Object[].class);
        //在调用putLong方法的时候出现了bug，还没有解决，正常的逻辑是这样
        getUnsafe().putLong(array, baseOffset, address);
        return array[0];
    }

    private Unsafe getUnsafe() {
        return unsafe;
    }

    //normalize是一个为了正确内存地址使用，将有符号的int类型强制转换成无符号的long类型的方法。
     long normalize(int value) {
        if (value >= 0) return value;
        return (~0L >>> 32) & value;
    }

    private  long sizeOf(Object o) throws NoSuchFieldException, IllegalAccessException {
        Field theUnsafe = Unsafe.class.getDeclaredField("theUnsafe");
        theUnsafe.setAccessible(true);
        Unsafe unsafe = (Unsafe) theUnsafe.get(null);

        HashSet<Field> fields = new HashSet();
        Class c = o.getClass();
        while (c != Object.class) {
            for (Field field : c.getDeclaredFields()) {
                if ((field.getModifiers() & Modifier.STATIC) == 0) {
                    fields.add(field);
                }
            }
            c = c.getSuperclass();
        }
        long maxSize = 0;
        for (Field field : fields) {
            //返回偏移量,每一个字段是4，偏移量没有根据方法的增加而变多
            long offset = unsafe.objectFieldOffset(field);
            if (offset > maxSize) {
                maxSize = offset;
            }
        }
        return ((maxSize / 8) + 1) * 8;
    }

}
`

Thanks.

**Comment by ZZD3627** [comment] 2022-05-17 14:09
> Hello, Can you provide some more context on this issue? The full hs_err log would be helpful as well as any information about the code being executed that you can share.
> 
> Tha

**Comment by lutkerd** [comment] 2022-05-18 15:49
The provided hs_err and the original snippet in the issue don't match, does this manifest in a few different crash signatures?
Also, Can you also share your implementation of Guard?

**Comment by ZZD3627** [comment] 2022-05-19 12:00
Here‘s the  implementation of Guard:
`

class Guard {
    private int ACCESS_ALLOWED = 1;

    public boolean giveAccess() {
        return 42 == ACCESS_ALLOWED;
    }

}

`
I don't know clear for  the mean of ‘signatures’ , can you explain it?

**Comment by lutkerd** [comment] 2022-05-19 16:44
The original snippet of the hr_err in the issue mentions: `# V  [libjvm.so+0x703032]  jni_IsInstanceOf+0x82`, but the hs_err you attatched has `# V  [libjvm.so+0x81b66f]  LinkResolver::resolve_invokevirtual(CallInfo&, Handle, constantPoolHandle, int, Thread*)+0x1ff`

When I reproduce locally, I am only seeing the `LinkResolver::resolve_invokevirtual` crash and just want to make sure we have all of details correct.

**Comment by ZZD3627** [comment] 2022-05-20 02:15
This is my fault. I delete the original hs_err log, and run the codes again. The hs_err log in the attachment is the result of another execution of the same program.

**Comment by simonis** [comment] 2022-05-20 11:14
As the name implies, the `sun.misc.Unsafe` API is inherently unsafe. It is not intended for user code and if you use it in user code it is your sole responsibility to make it work because the JVM can't provide any safety guarantees in that case.

Your code makes several assumption which are not true in general and and in the end lead to crashes:
- in `toAddress()` you try to get the address of an object by saving it at index 0 of an array and using `Unsafe.getInt()` to read the reference at index 0 of that array. This assumes that you are either using a 32-bit JVM or that you are running in compressed oops mode, otherwise the reference will be 64 bit wide. Even if you are running with compressed oops you can't be sure if the reference is a pure, 32-bit reference, if it has to be shifted or if it has to be shifted and added to a base address (these are the three compressed oops modes which are selected automatically based on heap size and memory availability in the address range below 32gb). If you run my standalone, instrumented version of [ShallowCopyTest.zip](https://github.com/corretto/corretto-8/files/8738632/ShallowCopyTest.zip) you'll see the following:
   ```
   $ java -Xlog:coops*=trace -XX:+UseSerialGC -Xmx100m -cp ~/Java/ ShallowCopyTest
   [0.028s][trace][gc,heap,coops] Trying to allocate at address 0x00000000f9c00000 heap of size 0x6400000
   [0.028s][debug][gc,heap,coops] Heap address: 0x00000000f9c00000, size: 100 MB, Compressed Oops mode: 32-bit
   size = 16
   baseOffset = 16
   array[0] = 0xf9c868d8
   start = 0xf9c868d8
   address = 0x7ffff00cb0d0
   #
   # A fatal error has been detected by the Java Runtime Environment:
   ...
   # Problematic frame:
   # V  [libjvm.so+0xa98461]  LinkResolver::resolve_invoke(CallInfo&, Handle, constantPoolHandle const&, int, Bytecodes::Code, JavaThread*)+0x541
   ```
   With a 100m heap, the JVM will choose the 32 bit compressed oops mode which means that the start address you compute (`0xf9c868d8`) is indeed within the Java heap which starts at `0x00000000f9c00000`. So this part is correct but the JVM still crashes in `LinkResolver::resolve_invoke()` and we'll see later why.
   If you're running with a 10000m heap, the JVM will choose the zero-based compressed oops mode with a shift amount of 3:
   ```
   $ java -Xlog:coops*=trace -XX:+UseSerialGC -Xmx10000m -cp ~/Java/ ShallowCopyTest
   [0.022s][trace][gc,heap,coops] Trying to allocate at address 0x000000058f000000 heap of size 0x271000000
   [0.022s][debug][gc,heap,coops] Heap address: 0x000000058f000000, size: 10000 MB, Compressed Oops mode: Zero based, Oop shift amount: 3
   size = 16
   baseOffset = 16
   array[0] = 0xb1e10cff
   start = 0xb1e10cff
   address = 0x7ffff00c31b0
   #
   # A fatal error has been detected by the Java Runtime Environment:
   ...
   # Problematic frame:
   # v  ~StubRoutines::jbyte_disjoint_arraycopy
   ```
   In this case, the object address you read (`0xb1e10cff`) isn't even 4-byte aligned, so it can hardly be the start address of an object. Instead you would first have to shift it three times to the left (i.e. `0xb1e10cff << 3` = `0x58f0867f8`) to get the real address of the object in the heap (which starts at `0x000000058f000000`). Because the computed source address is already wrong, the program already crashes during the copy step (i.e. `Unsafe.copyMemory()` calls `jbyte_disjoint_arraycopy()` which crashes).
- Your code assumes that `Unsafe.allocateMemory()` will return a 32-bit address (i.e. an address below 2^32). But this isn't guaranteed and as you can see from the output above, the address of the allocated memory `0x7ffff00c31b0` is indeed much larger. However, as we've seen before, if you are running in compressed oops mode, references will only be 32-bit long. So `return array[0]` in `fromAddress()` will only return 32-bit of the 64-bit destination address which you've previously allocates with `Unsafe.allocateMemory()` and written into the array with `Unsafe.putLong()`. As a result, you'll return a bogus object and the JVM crashes while it tries to dispatch the call to `toString()` on that bogus object:
   ```
   V  [libjvm.so+0xa98461]  LinkResolver::resolve_invoke(CallInfo&, Handle, constantPoolHandle const&, int, Bytecodes::Code, JavaThread*)+0x541
   V  [libjvm.so+0x84ccc1]  InterpreterRuntime::resolve_invoke(JavaThread*, Bytecodes::Code)+0x321
   V  [libjvm.so+0x84d0e5]  InterpreterRuntime::resolve_from_cache(JavaThread*, Bytecodes::Code)+0x105
   j  ShallowCopyTest.testShallowCopy()V+41
   j  ShallowCopyTest.main([Ljava/lang/String;)V+0
   ```

One way to fix your code for the non-compressed oops mode would be to replace the call to `Unsafe.getInt()` by a call to `Unsafe.getLong()` in `toAddress()`:
```
$ java -Xlog:coops*=trace -XX:+UseSerialGC -Xmx100m -XX:-UseCompressedOops -cp ~/Java/ ShallowCopyTest
size = 16
baseOffset = 16
array[0] = 0xd2dc7188
start = 0x7fffd2dc7188
address = 0x7ffff00d2080
Guard@1be6f5c3
```
But then again, this would only work in non-compressed oops mode. Also storing objects off-heap isn't a great idea either, because all the reference they contain will be invalidated, once  the GC moves the objects they are pointing to. Also, the JVM will probably already crash much earlier during GC, when GC is traversing the tree of live objects because the GC is not prepared to handle off-heap objects.

**Closed as completed by simonis** 2022-05-20 11:14 UTC

**Comment by ZZD3627** [comment] 2022-05-20 13:24
Thanks.

**Comment by ZZD3627** [comment] 2022-05-20 13:24
Thanks.
