### ISSUE TITLE
Java2D rendering may break when using soft clipping effects

### ISSUE THREAD

**Issue by aterai** [corretto/corretto-8#127] opened 2019-05-13 11:15 UTC
### Describe the bug
A soft clipping effects using an intermediate images and `AlphaComposite.SrcAtop` rules may cause Java 2D rendering to collapse.

For example, it seems to occur when the size of the cutout `Shape` is a multiple of `32`.

### To Reproduce
```
import java.awt.*;
import java.awt.geom.RoundRectangle2D;
import java.awt.image.BufferedImage;
import javax.swing.JFrame;
import javax.swing.JPanel;

public class SoftClippingTest extends JPanel {
  // private static final int SIZE = 30 * 5; // = 150; // OK
  private static final int SIZE = 32 * 5; // = 160; // NG
  private final BufferedImage image;

  public SoftClippingTest() {
    super();
    image = new BufferedImage(SIZE, SIZE, BufferedImage.TYPE_INT_ARGB);
    Graphics2D g2 = image.createGraphics();
    // BufferedImage img = null;
    // try {
    //   img = javax.imageio.ImageIO.read(getClass().getResource("test.png"));
    // } catch (Exception ex) {
    //   ex.printStackTrace();
    // }
    // g2.drawImage(img, null, 0, 0);
    g2.setPaint(Color.ORANGE);
    g2.fillRect(0, 0, SIZE, SIZE);
    g2.dispose();
  }

  @Override public void paintComponent(Graphics g) {
    super.paintComponent(g);
    Graphics2D g2 = (Graphics2D) g.create();

    GraphicsConfiguration gc = g2.getDeviceConfiguration();
    BufferedImage buf = gc.createCompatibleImage(SIZE, SIZE, Transparency.TRANSLUCENT);
    Graphics2D g2d = buf.createGraphics();

    g2d.setComposite(AlphaComposite.Src);
    g2d.setRenderingHint(RenderingHints.KEY_ANTIALIASING,
                         RenderingHints.VALUE_ANTIALIAS_ON);
    g2d.fill(new RoundRectangle2D.Float(0f, 0f, SIZE, SIZE, 32f, 32f));

    g2d.setComposite(AlphaComposite.SrcAtop);
    g2d.drawImage(image, 0, 0, null);
    g2d.dispose();

    g2.drawImage(buf, null, (getWidth() - SIZE) / 2, (getHeight() - SIZE) / 2);
    g2.dispose();
  }

  public static void main(String[] args) {
    EventQueue.invokeLater(() -> {
      JFrame f = new JFrame();
      f.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
      f.getContentPane().add(new SoftClippingTest());
      f.setSize(320, 240);
      f.setLocationRelativeTo(null);
      f.setVisible(true);
    });
  }
}
```

### Expected behavior
The tests should be executed correctly like OpenJDK Runtime Environment Corretto-11.0.3.7.1 (build 11.0.3+7-LTS)

### Screenshots
![SoftClippingTest](https://user-images.githubusercontent.com/2842060/57616686-b950f180-75b9-11e9-91e0-ad967d7d4942.png)

### Platform information
    OS: Microsoft Windows [Version 10.0.17763.437]
    Version: OpenJDK Runtime Environment Corretto-8.212.04.2 (build 1.8.0_212-b04)

### Additional context
Works fine for me on Windows10 using OpenJDK Runtime Environment (AdoptOpenJDK)(build 1.8.0_212-b03).

**Comment by alvdavi** [comment] 2019-05-13 23:50
Run the test on Windows 32 bits. It seems to be a problem added on 212 (right), as I'm not reproducing the issue with 202 (left):

![image](https://user-images.githubusercontent.com/12403364/57661281-ff4c8c00-759e-11e9-9603-e9f4ff4a38e1.png)

**Comment by EricEdens** [comment] 2019-05-20 22:29
Quick update -- we've identified that this regression was caused by https://github.com/corretto/corretto-8/commit/57da39ce6756d8d25ee63246c3909ae107ae8452 and we're targeting a fix in 8u222, which is scheduled for July 16, 2019.

**Comment by tustin2121** [comment] 2019-07-31 22:54
I was about to add a new issue when I found this bug report. Any estimate on when this fix will be released?

![image](https://user-images.githubusercontent.com/794812/62252277-63256a80-b3c0-11e9-995a-dff0f2de278f.png)
(We discovered that the bug only occurs when it is a multiple of 32 pixels wide. The cyan and yellow rectangles are 255 pixels wide)

**Comment by alvdavi** [comment] 2019-07-31 23:12
Hi,

Indeed the problem only happens when working with multiples of 32. The information we have for this bug can be found in the relevant OpenJDK issue, [JDK-8225065](https://bugs.openjdk.java.net/browse/JDK-8225065).

In any case, which version of Corretto are you using? In our recent releases (8.222.10.x) this problem should not appear. Unfortunately, this means another, older bug could resurface, but the conditions for that bug to appear are significantly harder.

Thanks

**Comment by tustin2121** [comment] 2019-08-01 20:05
You're right, it is fixed in the latest version. I didn't think it would be given the timestamps on the release vs the reversion commit (the commit happening 2 days after the release tag), and also this bug still being open. Sorry to bother you guys.

**Comment by alvdavi** [comment] 2019-08-01 20:07
Yes, this issue should be closed, thanks. Should you encounter a RasterFormatException in this version, please feel free to open a new issue and mention me directly.

**Closed by alvdavi** 2019-08-01 20:07 UTC
Labels: bug, pending release
