### ISSUE TITLE
Ellipse Fragmentation Drawing w/ Antialiasing

### ISSUE THREAD

**Issue by mtpresley** [corretto/corretto-8#128] opened 2019-05-20 21:15 UTC
### Describe the bug

Drawing ellipse (either drawOval or drawShape with Ellipse2D) fragments at certain sizes when antialiasing. 

### To Reproduce
Run program below and resize window slowly and either ellipse fragments at various sizes.

public class Tester extends JPanel {

	public Tester() {
		setBackground(Color.black);
		setPreferredSize(new Dimension(100,100));
	}
	
	@Override public void paintComponent(Graphics og) {
		super.paintComponent(og);
		
		Graphics2D g = (Graphics2D)og;
        g.setRenderingHint(RenderingHints.KEY_ANTIALIASING, RenderingHints.VALUE_ANTIALIAS_ON);

		g.setColor(Color.green);
		
		g.drawOval(0, 0, getWidth() - 4, getHeight() - 4);
	
		Ellipse2D el = new Ellipse2D.Float( getWidth()/4.0f, getHeight()/4.0f, getWidth()/2.0f, getHeight()/2.0f);
	
		g.draw(el);
	}

	
	public static void main(String[] args) {
		JFrame frame = new JFrame();
		frame.add(new Tester());
		
		frame.pack();
		frame.setVisible(true);
	}
}

### Expected behavior
Expect proper antialiases ellipses.

### Screenshots

![Screen Shot 2019-05-20 at 2 09 28 PM](https://user-images.githubusercontent.com/50847793/58052147-ed239e00-7b08-11e9-8b78-13e2072ce233.png)
![Screen Shot 2019-05-20 at 2 09 34 PM](https://user-images.githubusercontent.com/50847793/58052148-ed239e00-7b08-11e9-95e1-3bd8314c5484.png)

### Platform information
OS: Mac OS X 10.12.6
Version: 
OpenJDK Runtime Environment Corretto-8.212.04.2 (build 1.8.0_212-b04)
OpenJDK 64-Bit Server VM Corretto-8.212.04.2 (build 25.212-b04, mixed mode)

### Additional context
Remove the antialias hint and it works properly.

**Comment by mtpresley** [comment] 2019-05-20 21:17
Looks like it could be similar to https://github.com/corretto/corretto-8/issues/127

**Comment by mtpresley** [comment] 2019-05-20 21:50
Adding this line immediately before drawing the oval or creating the 2D Ellipse seems to fix, so I think it has the same underlying cause as #127:

if ( (((int)w) + 1) % 32 == 0) w++;

**Comment by EricEdens** [comment] 2019-05-20 22:29
@mtpresley  -- thanks for the report. What's the impact on your side?

**Comment by mtpresley** [comment] 2019-05-20 23:19
Have to put in work-arounds on several graphical elements, including polylines, arcs, rounded corners, ellipses, etc. Kind of a big deal since hard to find consistent mechanism to detect and remedy. For example, the fix for ellipses doesn't work for polylines (though a similar fix). Also, fix for ellipses doesn't work if the rendering hints includes STROKE control. Major hassle.

**Comment by EricEdens** [comment] 2019-05-28 22:20
As an update, we're targeting the quarterly 8u222 release in July as a fix for this. To consolidate issues, I'm going to close this as a duplicate of https://github.com/corretto/corretto-8/issues/127 .

**Closed by EricEdens** 2019-05-28 22:20 UTC
