### ISSUE TITLE
JAVA_HOME/PATH and empty folder remains after uninstall Corretto x86 and x64

### ISSUE THREAD

**Issue by yamadamn** [corretto/corretto-8#38] opened 2019-01-12 10:55 UTC
### Describe the bug
I uninstalled both Corretto x86/x64 in Windows;
But the JAVA_HOME and PATH environment variable remains, and the installed directory remains empty.

### To Reproduce
1. Install both Corretto x86/x64 in Windows (with default option)
2. Uninstall both Corretto x86/x64.

### Expected behavior
Both JAVA_HOME and PATH (x86/x64) environment will be removed after uninstall.

### Screenshots
![after-uninstall-java_home path folder](https://user-images.githubusercontent.com/3313661/51072422-d1fcd980-16a3-11e9-999f-066131f60c67.png)

It depends on install/uninstall order.

### Platform information
    OS: Windows 10
    Version "build 1.8.0_192-amazon-corretto-preview2-b12"

### Additional context
This issue is related to #15, #22 and #37 .

**Comment by davecurrie** [comment] 2019-01-17 20:04
Hi @yamadamn. Thanks for letting us know, we're taking a deeper look and will get back with an answer soon.

**Comment by yoroto** [comment] 2019-01-26 05:32
Hi @yamadamn ,
 
Thank you for submitted the issue!
 
This is actually an known issue of Windows 10. You can find the Microsoft KB here: https://support.microsoft.com/en-us/help/3166232/windows-installer-package-doesn-t-update-system-environment-variables If you log off and log in again, you should see the environment variables get updated and the folder get removed. Otherwise you can apply the Microsoft hotfix mentioned in the post. Let me know whether it works for you.

We will also look into adding an option to warn Windows 10 customer to sign off after uninstall if the hotfix is not present. So I will leave this issue open until we added the improvement.

**Comment by yoroto** [comment] 2019-02-07 17:24
Hi @yamadamn 

I have managed to reproduce your issue. The root cause was because the x86 and x64 MSIs share some installer code, and therefore are having the same IDs for some installation components. When you uninstall both of them, it confused the msiexec on which one to remove.

We will try to fix this in future releases. Thank you for submitting the issue!

**Comment by EricEdens** [comment] 2019-04-15 22:11
@yoroto : When you look at this, it also happens when updating an existing MSI. Here are the steps that I did:

1. Install 64-bit 8u202 MSI
2. Install 64-bit 8u212 MSI
3. Uninstall 64-bit 8u202

Below is a screenshot of the environment variable editor in Windows 10:

![image](https://user-images.githubusercontent.com/575626/56168578-7a1a8b00-5f90-11e9-8470-48554c22e5f2.png)

**Comment by cliveverghese** [comment] 2019-07-25 18:00
This issue was resolved in 8.222.x.x. Closing the issue.

**Closed by cliveverghese** 2019-07-25 18:00 UTC
Labels: bug
