### ISSUE TITLE
Code signing error when building DMG on Mac using JavaFX

### ISSUE THREAD

**Issue by jasonsobanski** [corretto/corretto-8#72] opened 2019-02-20 18:29 UTC
We have a JavaFX app that we have been creating native installers with using the self-contained application packaging features of JavaFX.  This has been working fine with the Oracle 8 JDK but we'd like to use Corretto instead.  It seems to be working fine on Windows and Linux (Ubuntu at least), but we've run into a problem when creating our Mac DMG file.  We sign our app using our certificate from Apple, but with Corretto we're running into a signing problem with one specific file inside the Java runtime that is being packaged into the app.  We use the JavaFX ANT task to kick off the build, here is the output of the error message -

Running [codesign, -s, Developer ID Application: MyApp, --prefix, MyApp., -vvvv, /var/folders/v5/0kbp6vx91t9_gvwpmvylgzl40000gn/T/fxbundler4199892105047409681/images/image-3802277374881889776/MyApp.app/Contents/PlugIns/Java.runtime/Contents/Home/jre/lib/libfreetype.dylib.6]

/var/folders/v5/0kbp6vx91t9_gvwpmvylgzl40000gn/T/fxbundler4199892105047409681/images/image-3802277374881889776/TestNav.app/Contents/PlugIns/Java.runtime/Contents/Home/jre/lib/**libfreetype.dylib.6: is already signed**

java.io.IOException: Exec failed with code 1

### To Reproduce
I don't have code since this is more of a packaging/signing issue, but I'd expect it to happen with any Mac DMG created via JavaFX as the file that can't be signed is inside the JRE itself.

### Expected behavior
The code signing will complete and the DMG will be created.

### Platform information
    OS: macOS 10.14.3
    Version: build 1.8.0_202-b08

### Additional context
I tried to force a signature using my certificate over the existing signature on the file, but that didn't help.  I believe if the codesign call isn't including the -f flag to force a signature, this will always fail if any of the files in the app are already signed.  Based on the OpenJDK code I would have expected only *.dylib files to try and be signed as part of the packaging steps, so I'm not sure why  this *.6 file was included (even if it really is a dylib file).  I found that I could manually strip the signing off the file in the install location of Corretto and then my build process didn't have any issues signing libfreetype.dylib.6.  While this works for now and my app seems to run fine using Corretto, it doesn't seem like a great long term solution.  This was the only file that has this issue, all the other JRE files packaged into the app seem fine.

**Comment by navyxliu** [comment] 2019-02-21 20:00
@jasonsobanski  Thanks for bringing this up. We'll verify this and update the issue when we have more information on a fix.

**Comment by ziyiluo** [comment] 2019-02-21 20:04
Hi Jason, thanks for reporting the issue. The root cause is that Corretto 8 uses the freetype bundled in X11 (Xquartz) and the freetype dynamic library from Xquartz is signed. During the build of Corretto 8, the freetype.dylib.6 is directly copied from the freetype library, therefore, contains the signature which other dynamic libraries in Corretto 8 do not have. We will fix that by building Corretto with an unsigned freetype in future releases. Unfortunately I have not found a safe quick workaround for you to "unsign" the dylib file on your local host. [This](https://reverseengineering.stackexchange.com/questions/13622/remove-code-signature-from-a-mac-binary) stack exchange question provides two potential workarounds but both may leave the binary unable to be re-signed with the codesign tool. We will keep investigating.

**Comment by davecurrie** [comment] 2019-03-12 19:45
Just to update the issue, this is planned to be fixed in the next release.

**Comment by ziyiluo** [comment] 2019-04-18 07:07
Fixed in 8.212.04.1 release.

**Closed by ziyiluo** 2019-04-18 07:07 UTC
Labels: bug
